In [9]:
import numpy as np
a = [[10,20,40,20],[10,30,40,50]]
arr=np.array(a)
print(arr)
print(arr.shape)
print(len(arr))
print(np.size(arr))
print(type(arr))
print(arr.astype(float))


[[10 20 40 20]
 [10 30 40 50]]
(2, 4)
2
8
<class 'numpy.ndarray'>
[[10. 20. 40. 20.]
 [10. 30. 40. 50.]]


In [15]:
arr1 = np.array ([3,4,6,2])
arr2 = np.array([2,2,3,1])
print(arr1+arr2)
print(np.add(arr1,arr2))
print(arr1-arr2)
print(np.power(arr1,arr2))
print(np.sqrt(arr1))

[5 6 9 3]
[5 6 9 3]
[1 2 3 1]
[  9  16 216   2]
[1.73205081 2.         2.44948974 1.41421356]


In [16]:
arr1 = np.array ([3,4,6,2])
arr2 = np.array([2,2,3,1])
print(np.concatenate([arr1,arr2]))

[3 4 6 2 2 2 3 1]


In [22]:
arr1 = np.array ([[3,4,6,2],[20,22,33,11]])
arr2 = np.array([[2,2,3,1],[2,4,5,11]])
print(np.concatenate([arr1,arr2], axis=1))
print(np.concatenate([arr1,arr2], axis=0))

[[ 3  4  6  2  2  2  3  1]
 [20 22 33 11  2  4  5 11]]
[[ 3  4  6  2]
 [20 22 33 11]
 [ 2  2  3  1]
 [ 2  4  5 11]]


In [25]:
arr1 = np.array ([3,4,6,2,20,22,33,11])
b = np.array_split (arr1,4)
print(b)

[array([3, 4]), array([6, 2]), array([20, 22]), array([33, 11])]


In [34]:
a = np.array ([[3,4,6,2],[20,22,33,11]])
print (np.append(a,[10,20]))
print (np.insert(a,1,[20,3,2,4],axis =0))
print (np.insert(a,1,[20],axis =1))

[ 3  4  6  2 20 22 33 11 10 20]
[[ 3  4  6  2]
 [20  3  2  4]
 [20 22 33 11]]
[[ 3 20  4  6  2]
 [20 20 22 33 11]]


In [35]:
arr1 = np.array ([3,4,6,2,20,22,33,11])
print(np.sort(arr1))

[ 2  3  4  6 11 20 22 33]


In [41]:
arr1 = np.array ([3,4,6,2,20,22,33,11])
print(np.sort(arr1))
s = np.where (arr1 %2== 0)
print(s)
fa = arr1>22
new = arr1[fa]
print(new)

[ 2  3  4  6 11 20 22 33]
(array([1, 2, 3, 4, 5]),)
[33]


In [46]:
arr1 = np.array ([3,4,6,2,20,22,33,11])
print(np.sum(arr1))
print(np.min(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

101
2
12.625
[  3   7  13  15  35  57  90 101]
[       3       12       72      144     2880    63360  2090880 22999680]


In [50]:
a = (100,200,300,400)
b= (1,3,4,6)
price = np.array(a)
qty = np.array (b)
print (np.cumprod([price,qty], axis = 0))
c = np.cumprod([price,qty], axis = 0)
print (c[1].sum())

[[ 100  200  300  400]
 [ 100  600 1200 2400]]
4300
